//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopCompost_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinCollection()
        {
            this.BinWeights = new HashSet<BinWeight>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> GreenBinCount { get; set; }
        public Nullable<int> GreyBinCount { get; set; }
        public Nullable<int> BlueBinCount { get; set; }
        public int CollectionDurationInMinutes { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinWeight> BinWeights { get; set; }
    }
}
