//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopCompost_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinProcessing
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> BinNumber { get; set; }
        public Nullable<int> MeatPercentage { get; set; }
        public Nullable<int> ProducePercentage { get; set; }
        public Nullable<int> BulkPercentage { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
