//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopCompost_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinWeight
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int BinCollectionId { get; set; }
        public Nullable<int> BinWeight1 { get; set; }
    
        public virtual BinCollection BinCollection { get; set; }
        public virtual Client Client { get; set; }
    }
}
