//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopCompost_DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopCompost_DbEntities : DbContext
    {
        public HopCompost_DbEntities()
            : base("name=HopCompost_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinCollection> BinCollections { get; set; }
        public virtual DbSet<BinWeight> BinWeights { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<BinProcessing> BinProcessings { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
    }
}
